[irc.server]
host = "irc.server.example"
port = 6667
ssl = false

[irc.bot]
nickname = "syslog"
realname = "syslog"

[irc]
channels = [
  { name = "#examplechannel1" },
  { name = "#examplechannel2", password = "zePassword" },
]
